### ISSUE TITLE
starting docker image with --autosave causes crontab.db to grow continuously

### ISSUE THREAD

**Issue by holygekko** [alseambusher/crontab-ui#189]
I've created a fork with the only change being adding `--autosave` to `command=node /crontab-ui/app.js` in `supervisord.conf`
This way the crontabs get autostarted after a container restarts.

I noticed however that crontab.db keeps growing and growing. It continuously adds the same commands to the file. It got to 900mb in a two months.

What causes this and what can i do to prevent it?

**Comment by rodriciru** [comment]
It still happens...

**Comment by rodriciru** [comment]
It turns out that it's not a bug, it's a desired behavior, but annoying and possibly causing some trouble.
Crontab-ui uses a database called nedb.
Apparently, it is much more "expensive" (in terms of time) to rewrite the entire database (which is a JSON) every time you do an update or a delete, than to add a line at the end of the file and then let the engine do what it has to do. The engine will compact the database when the app is restarted and that's it.
If you notice, if you reload the ui (with a F5) of crontab-ui, the database gets smaller.
But as I guess you don't get into the ui every 10 minutes, the engine has an option to auto compact the db every X milliseconds.
Just add `db.persistence.setAutocompactionInterval(interval);` on line 13 of crontab.js (just below `var db = new Datastore({ filename: exports.crontab_db_file});`) and the engine will compact the database every X milliseconds and you're done.

**Comment by rodriciru** [comment]
Likewise all this is due to an infinite loop which is as follows:

- Every time the database is modified in any way, node.js calls a method
- That method, writes some files, runs the cron and does an update to the database
- The database is modified and it starts all over again.

**Comment by rodriciru** [comment]
I create a PR about that issue
https://github.com/alseambusher/crontab-ui/pull/214
